[player]
# Name to display under player
name = "Player"



[teams]
# Color of team one
#
# default: { r = 0.0, g = 0.0, b = 1.0, a = 1.0 }
team_one_color = { r = 0.0, g = 0.0, b = 1.0, a = 1.0 }

# Color of team two
#
# default { r = 1.0, g = 0.0, b = 0.0, a = 1.0 }
team_two_color = { r = 1.0, g = 0.0, b = 0.0, a = 1.0 }



[camera]
# How much bias toward the center the camera has
#
# Can be any float between 0.0 (camera only based
# on players) to 1.0 (camera always centered)
#
# default: 0.7
bias = 0.7

# How zoomed in the camera is
#
# Can be any positive float
#
# default: 1.1
zoom = 1.1

# Sync frame rate to display refresh rate
# 
# default: true
vsync = false

# Display name above player
#
# default: false
player_name_above = false



[client]
# IP address to host client on (should usually not be changed)
#
# default: "0.0.0.0"
ip = "0.0.0.0"

# Port to use when connecting to a server
#
# 0 means letting the operating system choose
#
# default: "0"
port = "0"



[server]
# IP adress clients should connect to
#
# default: "0.0.0.0"
ip = "0.0.0.0"

# Port to serve
#
# default: "4000"
port = "4000"

# Team size
#
# Only read when hosting server
#
# default: 1
team_size = 1
