[package]
name = "game_config"
version = "0.1.0"
edition = "2024"

[dependencies]
foundation = { path = "../foundation" }
anyhow = "1.0.100"
serde = { version = "1.0.228", features = ["derive"] }
toml = "0.9.8"
